/*******************************************************************
389. Find the Difference ==136. Single Number  
Total Accepted: 8895
Total Submissions: 17674
Difficulty: Easy
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
**********************************/
class Solution {
public:
    char findTheDifference(string s, string t) {
        string r = s+t;
        char o=0;
        for(int i=0; i<r.length(); i++){
            o ^= r[i];
        }
        return o;
    }
};
